name: 'AWS SSM Parameter Store GetParameters Action'
description: 'A GitHub action for AWS Systems Manager Parameter Store GetParameters call and placing the results into environment variables'
author: 'Derek Kershner'
inputs:
    parameterPairs:
        required: true
        description: 'The parameters you would like to retrieve, in pair format with an equal in between and comma delimited. The parameter name is the key, and the environment variable name is the value.'
    withDecryption:
        required: false
        description: 'Whether to decrypt SecretString SSM parameters. Defaults to true.'
        default: 'true'

runs:
    using: 'node12'
    main: 'dist/index.js'
branding:
    icon: 'lock'
    color: 'blue'
